# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cantango-api"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2011-11-25"
  s.description = "Ability, Can, Scope, Session, User, Account and more APIs for CanTango"
  s.email = "kristian@unity3d.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "cantango-api.gemspec",
    "lib/cantango/api.rb",
    "lib/cantango/api/ability.rb",
    "lib/cantango/api/ability/account.rb",
    "lib/cantango/api/ability/user.rb",
    "lib/cantango/api/account.rb",
    "lib/cantango/api/attributes.rb",
    "lib/cantango/api/can.rb",
    "lib/cantango/api/can/account.rb",
    "lib/cantango/api/can/user.rb",
    "lib/cantango/api/common.rb",
    "lib/cantango/api/model.rb",
    "lib/cantango/api/model/account.rb",
    "lib/cantango/api/model/user.rb",
    "lib/cantango/api/options.rb",
    "lib/cantango/api/scope.rb",
    "lib/cantango/api/scope/account.rb",
    "lib/cantango/api/scope/user.rb",
    "lib/cantango/api/session.rb",
    "lib/cantango/api/session/account.rb",
    "lib/cantango/api/session/user.rb",
    "lib/cantango/api/user.rb",
    "spec/cantango/api/ability/account_spec.rb",
    "spec/cantango/api/ability/user_spec.rb",
    "spec/cantango/api/account_spec.rb",
    "spec/cantango/api/attributes_spec.rb",
    "spec/cantango/api/can/account_spec.rb",
    "spec/cantango/api/can/user_spec.rb",
    "spec/cantango/api/options_spec.rb",
    "spec/cantango/api/scope/account_spec.rb",
    "spec/cantango/api/scope/user_spec.rb",
    "spec/cantango/api/user_spec.rb",
    "spec/cantango/api_spec.rb",
    "spec/cantango_api_spec.rb",
    "spec/fixtures/models.rb",
    "spec/fixtures/models/admin.rb",
    "spec/fixtures/models/admin_account.rb",
    "spec/fixtures/models/items.rb",
    "spec/fixtures/models/permission.rb",
    "spec/fixtures/models/project.rb",
    "spec/fixtures/models/simple_roles.rb",
    "spec/fixtures/models/user.rb",
    "spec/fixtures/models/user_account.rb",
    "spec/helpers/current_user_accounts.rb",
    "spec/helpers/current_users.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/cantango-api"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "The main API for CanTango"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<sweetloader>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<cantango-config>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_dependency(%q<sweetloader>, ["~> 0.1.0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<cantango-config>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
    s.add_dependency(%q<sweetloader>, ["~> 0.1.0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<cantango-config>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.1.rc"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

